depot/config/routes.rb
Depot::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
      resources :users
      resources :orders
      resources :line_items
      resources :carts
      get "store/index"
      resources :products do
        get :who_bought, on: :member
      end

      root 'store#index', as: 'store'

  end

end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= form_tag store_path, class: 'locale', method: :get do %>
      <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag 'logo.jpg' %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="current_info">
      <p class="time"><%= Time.now.strftime("%Y/%d/%m") %></p>
    </div>
    <div id="side">
      <% if @cart %>
        <div id="cart" style="display: none">
          <%= render @cart %>
        </div>
      <% end %>

      <ul>
        <li><a href="http://google.co.jp"><%= t('.home') %></a></li>
        <li><a href="http://google.co.jp"><%= t('.questions') %></a></li>
        <li><a href="http://google.co.jp"><%= t('.news') %></a></li>
        <li><a href="http://google.co.jp"><%= t('.contact') %></a></li>
      </ul>

      <% if session[:user_id] %>
      <ul>
        <li><%= link_to '注文', orders_path %></li>
        <li><%= link_to '商品', products_path %></li>
        <li><%= link_to 'ユーザ', users_path %></li>
      </ul>
      <%= button_to 'ログアウト', logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>